name: Infra

on:
  push

permissions:                            
  contents: read

jobs:
  setup-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          azcliversion: latest
          inlinescript: az account show
      - name: Install Azure ML CLI
        run: | 
          az config set extension.use_dynamic_install=yes_without_prompt
          az extension add -n ml -y
      - name: Run Infra.sh
        run: chmod +x infra/infra.sh
      - name: Run infra.sh
        run: infra/infra.sh



