name: Infra

on:
  push

permissions:                            
  contents: read
  id-token: write


jobs:
  setup-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Install Azure ML CLI
        run: | 
          az config set extension.use_dynamic_install=yes_without_prompt
          az extension add -n ml -y
      - name: Run Infra.sh
        run: chmod +x infra/infra.sh
              infra/infra.sh
              



